### ISSUE TITLE
loading 背景颜色修改

### ISSUE THREAD

**Issue by zhanwen** [ElemeFE/v-charts#419]
### Summary 简述
默认loading状态下白色背景不好看，想修改点，试了下 chartTheme没成功

### Expect 期望结果
改变背景颜色

**Comment by xiguaxigua** [comment]
可以通过 css 来设置：
```css
.v-charts-component-loading {
  background: rgba(255, 0, 0, .1)
}
```
