### ISSUE TITLE
针对页面zoom缩放问题，图表飘点位

### ISSUE THREAD

**Issue by smarttang** [ElemeFE/v-charts#858]
### Summary 简述
在zoom等于1的时候，创建图表没有问题，但是页面特别不好看，默认用command - 手动缩放页面是正常的，但是如果用css控制页面缩放，如：
```css
@media screen and (min-width: 1200px) {
  html {
    zoom: 79%;
  }
}
```
发现图表就不正常了，展现没问题，但是鼠标放上去，发现点位变了。
![image](https://user-images.githubusercontent.com/4961402/88129184-0c84f200-cc0a-11ea-932d-c46dcd2d2b2b.png)

### Expect 期望结果
在不同的zoom比例下，能够正常使用。

### Reproduce 重现示例

```css
@media screen and (min-width: 1200px) {
  html {
    zoom: 79%;
  }
}
@media screen and (min-width: 960px) and (max-width: 1199px) {
  html {
    zoom: 88%;
  }
}
@media screen and (min-width: 768px) and (max-width: 959px) {
  html {
    zoom: 98%;
  }
}
```

```html
vue上
          <div class="text" ref="highPortsRingBox">
            <ve-ring :data="portsData" ref="highPortsRing"></ve-ring>
          </div>

```
